### PR TITLE
fix: utils - change way to compute selector hash

### LINKED ISSUE #247: [Bug]: Client not in sync with torii grpc
### Dojo.js Version

1.0.0-alpha.0

### What happened?

Components in the react examples are not being updated from torii.
I'using the code below on my setup, as documented.

```js
const sync = await getSyncEntities(
    toriiClient,
    contractComponents as any,
    []
);
```

### What is the expected behavior?

Components / game state should always be in sync with torii.

### Steps to reproduce

The `react-phaser-example` example seems to be the only one not using overrides.
It relies on `getSyncEntities()` as exemplified above.

* Deploy dojo starter locally
* Run torii locally
* run the phaser client
* try to move the rock (WASD keys).
* Look at torii logs, it is being indexed!
* Game state is not updated.

As a side note, I understand overrides are useful sometimes, but we have to replicate game logic off-chain.
Moving a square on the screen is a good *override* example, but should not be THE Dojo example.
Newcomers will think we have to override every call, otherwise it will not be updated. That's a mistake I made when I started with Dojo, and it gave me a lot of headaches and fud on Torii.
It is my opinion there should be one specific example explaining how to do overrides, all the others should rely on Torii as the norm.

### Trace

_No response_

### Is there an existing issue for this?

- [ ] I have searched the existing issues and verified no issue exits for this problem.

### PR DESCRIPTION
**Pull request by MartianGreed**
Closes #247 

## Introduced changes

Changes way to get component from event hash.

This will not fix the recs issue about Map receiver.

-

## Checklist

-   [x] Linked relevant issue
-   [x] Added relevant tests
-   [x] Performed self-review of the code

## Summary by CodeRabbit

- **New Features**
  - Introduced enhanced logging and error handling in entity management functions.
  - Added a new test suite using Vitest for utility functions to ensure reliability.
  - Implemented new constants and functions for improved event filtering and component handling.

- **Bug Fixes**
  - Refined error handling in component setting logic to prevent issues during execution.

- **Chores**
  - Updated the testing framework from Jest to Vitest, enhancing testing capabilities.
  - Added coverage reporting for utility functions to improve quality assurance.

### CODE REVIEW

File: packages/state/src/recs/index.ts [hunk 1]
```diff
@@ -71,6 +71,7 @@ export const getEntities = async <S extends Schema>(
 
     while (continueFetching) {
         const entities = await client.getAllEntities(limit, cursor);
+        console.log(entities, components);
```
Comment (ponderingdemocritus) [inline packages/state/src/recs/index.ts:74]: we should remove this

**Comment by ponderingdemocritus** [comment]
Looks good other than that, nice iteration
